# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build APK
        run: |
         ./build.sh

      - name: Upload APK to Release 
        uses: softprops/action-gh-release@master
        with:
         files: |
          /home/runner/work/treble_app/treble_app/*.apk
         name: PHH Treble Settings APP
         tag_name: ${{ github.run_id }}
