name: Phh Treble Settings App Build

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]  # Automatically build on pushes to main branches
    paths:
      - '**.java'
      - '**.xml'
      - '**.gradle'
      - 'build.sh'
  pull_request:
    paths:
      - '**.java'
      - '**.xml'
      - '**.gradle'
      - 'build.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for better versioning
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for build script
        run: chmod +x ./build.sh
          
      - name: Build APK
        run: ./build.sh
        id: build
        
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: |
            **/*.apk
          retention-days: 14
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'  # Only release on main branch
        with:
          files: |
            **/*.apk
          name: "Phh Treble Settings App $(date +'%Y-%m-%d %H:%M')"
          tag_name: "phh-${{ github.run_number }}"
          body: |
            Automated build of Phh Treble Settings App
            Build number: ${{ github.run_number }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
