name: Phh Treble Settings App Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build APK
        run: |
          chmod +x build.sh
          ./build.sh

      - name: List APK files
        run: |
          echo "Listing APK files in the directory..."
          ls -al treble_app/

      - name: Upload APK to Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            treble_app/*.apk
          name: Phh Treble Settings App
          tag_name: phh
